services:
  redis:
    image: redis
    ports:
      - 6379:6379
  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./docker/grafana:/var/lib/grafana
    env_file:
      - ./docker/grafana/grafana-config.env
    ports:
      - 3000:3000
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411