spring:
   profiles:
      active: dev
   data:
      redis:
         host: localhost
         port: 6379
api:
   endpoint:
      baseUrl: /api/v1


#logging:
#   level:
#      root: WARN
#      org:
#         springframework:
#            web: DEBUG
#         hibernate: ERROR