spring:
   application:
      name: magic
   datasource:
      url: jdbc:h2:mem:magic
      username: sa
      password:
   jpa:
    show-sql: true
api:
   endpoint:
      baseUrl: /api/v1

#logging:
#   level:
#      root: WARN
#      org:
#         springframework:
#            web: DEBUG
#         hibernate: ERROR